### ISSUE TITLE
Issue with grace + tuplet conversion

### ISSUE THREAD

**Issue by rigaux** [music-encoding/music-encoding#259]
This score: 
http://neuma.huma-num.fr/opus/timbres:cdc:0037
MusicXML: http://neuma.huma-num.fr/rest/timbres/cdc/0037/score.xml
MEI: http://neuma.huma-num.fr/rest/timbres/cdc/0037/mei.xml

Measures 5 and 9: each time, one note from the tuplet is missing, as well as the grace note

**Comment by ahankinson** [comment]
I believe this one is fixed now.

**Comment by pe-ro** [comment]
Partially fixed, I believe.  The stylesheet raises an error --

"Description: The attribute axis starting at an attribute node will never select anything
Start location: 10431:0"

and the problems reported in #258 aren't completely resolved; that is, the beamed grace notes in m. 4 and m. 5 aren't beamed properly.

**Comment by kepper** [comment]
will look into this asap. Paid no attention to #258 (yet).

Am 28.09.2015 um 19:42 schrieb pe-ro notifications@github.com:

**Comment by pe-ro** [comment]
Sorry, didn’t mean to get ahead of you.

## 

p.

**Comment by kepper** [comment]
All good. I hadn't noticed #258 as separate issue, so it's good you pointed me at it :-)

Am 28.09.2015 um 19:49 schrieb pe-ro notifications@github.com:

**Comment by ahankinson** [comment]
This issue was moved to music-encoding/encoding-tools#5
